Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.App
      CodeUri: E:\GitHub\2022\aws\hello-lambda\HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64