Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.App::hello
      CodeUri: C:\Users\JosueLubaki\OneDrive - Alithya\courses\Serverless\serverless-course\HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64