AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-lambda

  Sample SAM Template for hello-lambda
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: ca.josue.aws.lambda.DataTypes::getStudentScores
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512